export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';
export const PRODUCTS_PAGE = 'PRODUCTS_PAGE';
export const GET_PRODUCT = 'GET_PRODUCT';
